---
apiVersion: spotify.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: deveez-dev
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: provider-spotify-creds
      namespace: crossplane-system
      key: credentials

---
apiVersion: v1
kind: Secret
metadata:
  name: provider-spotify-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_key": "qwerty12345",
      "auth_server": "https://spotify-auth-proxy-593713512699.europe-southwest1.run.app"
    }
