apiVersion: playlist.spotify.crossplane.io/v1alpha1
kind: Playlist
metadata:
  annotations:
    crossplane.io/composition-resource-name: playlist
    crossplane.io/external-create-pending: "2024-09-25T11:12:51Z"
    crossplane.io/external-create-succeeded: "2024-09-25T11:12:51Z"
    crossplane.io/external-name: 7Hg6PTSOJGGSikod9vXJJH
    upjet.crossplane.io/provider-meta: "null"
  creationTimestamp: "2024-09-25T11:12:32Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: my-second-claim-9cgcs-
  generation: 2
  labels:
    crossplane.io/claim-name: my-second-claim
    crossplane.io/claim-namespace: crossplane-system
    crossplane.io/composite: my-second-claim-9cgcs
  name: crossplane-generated-playlist
  ownerReferences:
  - apiVersion: workshop.deveez.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XAlbum
    name: my-second-claim-9cgcs
    uid: 57038c50-16b7-46e7-b114-c825f2a3f2ab
  resourceVersion: "204265"
  uid: 348dd2f7-3dd2-4fc1-a7f4-02fd9046d6ab
spec:
  deletionPolicy: Delete
  forProvider:
    description: Created by duk
    name: This is a test playlist
    public: true
    tracks:
    - 5DZ4M3yMat79ok25rZHuA9
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: deveez-dev
status:
  atProvider:
    description: Created by duk
    id: 7Hg6PTSOJGGSikod9vXJJH
    name: This is a test playlist
    public: true
    snapshotId: AAAAAZ/vIyU7WCZterY8sgpNtwx7yiAW
    tracks:
    - 5DZ4M3yMat79ok25rZHuA9
  conditions:
  - lastTransitionTime: "2024-09-25T11:12:51Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-09-25T11:13:08Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-09-25T11:12:52Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
  - lastTransitionTime: "2024-09-25T11:12:52Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
