apiVersion: v1
kind: Namespace
metadata:
  name: spotify-auth-proxy

---
# Source: spotify-auth-proxy/templates/secret-api-key.yaml
apiVersion: v1
kind: Secret
metadata:
  name: spotify-auth-proxy-api-key
  namespace: spotify-auth-proxy 
  labels:
    helm.sh/chart: spotify-auth-proxy-0.2.1
    app.kubernetes.io/name: spotify-auth-proxy
    app.kubernetes.io/instance: spotify-auth-proxy
    app.kubernetes.io/version: "0.2.7"
    app.kubernetes.io/managed-by: Helm
data:
  spotifyProxyAPIKey: cXdlcnR5MTIzNDU=
---
# Source: spotify-auth-proxy/templates/secret-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: spotify-auth-proxy-credentials
  namespace: spotify-auth-proxy
  labels:
    helm.sh/chart: spotify-auth-proxy-0.2.1
    app.kubernetes.io/name: spotify-auth-proxy
    app.kubernetes.io/instance: spotify-auth-proxy
    app.kubernetes.io/version: "0.2.7"
    app.kubernetes.io/managed-by: Helm
data:
  spotifyClientID: YjQ0NTAwYzNhMjUxNGM1NGFkMTM0ZWNmYjYyM2I0YzI=
  spotifyClientSecret: ZWI0NDZhYzQ4NDAxNDgwOGExNmZjZDI5OGI5YzVjNDE=
---
# Source: spotify-auth-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spotify-auth-proxy
  namespace: spotify-auth-proxy
  labels:
    helm.sh/chart: spotify-auth-proxy-0.2.1
    app.kubernetes.io/name: spotify-auth-proxy
    app.kubernetes.io/instance: spotify-auth-proxy
    app.kubernetes.io/version: "0.2.7"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 27228
      targetPort: 27228
      protocol: TCP
      name: callback
  selector:
    app.kubernetes.io/name: spotify-auth-proxy
    app.kubernetes.io/instance: spotify-auth-proxy
---
# Source: spotify-auth-proxy/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spotify-auth-proxy
  namespace: spotify-auth-proxy
  labels:
    helm.sh/chart: spotify-auth-proxy-0.2.1
    app.kubernetes.io/name: spotify-auth-proxy
    app.kubernetes.io/instance: spotify-auth-proxy
    app.kubernetes.io/version: "0.2.7"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spotify-auth-proxy
      app.kubernetes.io/instance: spotify-auth-proxy
  template:
    metadata:
      labels:
        helm.sh/chart: spotify-auth-proxy-0.2.1
        app.kubernetes.io/name: spotify-auth-proxy
        app.kubernetes.io/instance: spotify-auth-proxy
        app.kubernetes.io/version: "0.2.7"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: spotify-auth-proxy
          securityContext:
            {}
          image: "ghcr.io/conradludgate/spotify-auth-proxy@sha256:d9f54a4d6faa2d3c32798808fffe69beb9713e560641c9ad79c8e20f1fa2bc86"
          imagePullPolicy: IfNotPresent
          ports:
            - name: callback
              containerPort: 27228
              protocol: TCP
          env:
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotify-auth-proxy-credentials
                  key: spotifyClientID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-auth-proxy-credentials
                  key: spotifyClientSecret
            - name: SPOTIFY_PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: spotify-auth-proxy-api-key
                  key: spotifyProxyAPIKey
          livenessProbe:
            httpGet:
              path: /health
              port: 27228
          readinessProbe:
            httpGet:
              path: /health
              port: 27228
          resources:
            {}
---
# Source: spotify-auth-proxy/templates/tests/test-external-secrets.yaml
---
---
# Source: spotify-auth-proxy/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "spotify-auth-proxy-test-connection"
  namespace: spotify-auth-proxy
  labels:
    helm.sh/chart: spotify-auth-proxy-0.2.1
    app.kubernetes.io/name: spotify-auth-proxy
    app.kubernetes.io/instance: spotify-auth-proxy
    app.kubernetes.io/version: "0.2.7"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['spotify-auth-proxy:27228//health']
  restartPolicy: Never
