apiVersion: v1
kind: Secret
metadata:
  name: provider-spotify-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_key": "S7aSh8Vo0dV3fkdOrdWIH6o-9xWLHU0SMJkHIoWaZsN8MvvxoWdUUFD5Bc0Pvu7i",
      "auth_server": "http://spotify-auth-proxy.spotify-auth-proxy.svc:27228"
    }
