apiVersion: spotify.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: deveez-dev
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: provider-spotify-creds
      namespace: crossplane-system
      key: credentials
