apiVersion: v1
kind: Secret
metadata:
  name: provider-spotify-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_key": "qwerty12345",
      "auth_server": "https://spotify-auth-proxy-593713512699.europe-southwest1.run.app"
    }
